[versions]
agp                    = "8.5.1"
kotlin                 = "1.9.23"
detekt                 = "1.23.6"
vanniktech-publish     = "0.29.0"
core-ktx               = "1.13.1"
annotation             = "1.7.1"
work                   = "2.9.0"
datastore              = "1.1.1"
lifecycle              = "2.8.4"
material               = "1.12.0"
jodatime               = "2.12.5"
coil                   = "2.7.0"
junit4                 = "4.13.2"
assertj                = "3.26.0"
org-json               = "20200518"
androidx-test-ext      = "1.2.1"
espresso               = "3.6.1"
kotlinx-coroutines     = "1.7.3"
mockk                  = "1.13.12"

[libraries]
androidx-core-ktx              = { module = "androidx.core:core-ktx",                          version.ref = "core-ktx" }
androidx-annotation            = { module = "androidx.annotation:annotation",                   version.ref = "annotation" }
androidx-work-runtime          = { module = "androidx.work:work-runtime-ktx",                   version.ref = "work" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences",         version.ref = "datastore" }
androidx-lifecycle-runtime     = { module = "androidx.lifecycle:lifecycle-runtime-ktx",         version.ref = "lifecycle" }
material                       = { module = "com.google.android.material:material",              version.ref = "material" }
jodatime                       = { module = "joda-time:joda-time",                              version.ref = "jodatime" }
coil                           = { module = "io.coil-kt:coil",                                  version.ref = "coil" }
junit4                         = { module = "junit:junit",                                       version.ref = "junit4" }
assertj-core                   = { module = "org.assertj:assertj-core",                          version.ref = "assertj" }
org-json                       = { module = "org.json:json",                                     version.ref = "org-json" }
androidx-test-ext-junit        = { module = "androidx.test.ext:junit",                          version.ref = "androidx-test-ext" }
androidx-test-espresso-core    = { module = "androidx.test.espresso:espresso-core",             version.ref = "espresso" }
androidx-work-testing          = { module = "androidx.work:work-testing",                        version.ref = "work" }
kotlinx-coroutines-core        = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core",    version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android     = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test        = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test",    version.ref = "kotlinx-coroutines" }
mockk                          = { module = "io.mockk:mockk",                                   version.ref = "mockk" }

[plugins]
android-application    = { id = "com.android.application",             version.ref = "agp" }
android-library        = { id = "com.android.library",                 version.ref = "agp" }
kotlin-android         = { id = "org.jetbrains.kotlin.android",        version.ref = "kotlin" }
detekt                 = { id = "io.gitlab.arturbosch.detekt",         version.ref = "detekt" }
vanniktech-publish     = { id = "com.vanniktech.maven.publish",        version.ref = "vanniktech-publish" }
